"use client";

import { useEffect, useMemo, useState } from "react";

type ActiveBoost = {
  multiplier: number;
  expiresAt: number;
};

export default function RewardsPage() {
  const [labBalance, setLabBalance] = useState(0);
  const [claimable, setClaimable] = useState(0);
  const [totalGameEarned, setTotalGameEarned] = useState(0);
  const [boost, setBoost] = useState<ActiveBoost | null>(null);
  const [now, setNow] = useState(Date.now());

  useEffect(() => {
    function loadData() {
      const savedBalance = Number(localStorage.getItem("wh_lab_balance") || 0);
      const savedClaimable = Number(localStorage.getItem("wh_claimable") || 0);
      const savedGameEarned = Number(localStorage.getItem("wh_total_game_earned") || 0);
      const savedBoostRaw = localStorage.getItem("wh_boost");

      setLabBalance(savedBalance);
      setClaimable(savedClaimable);
      setTotalGameEarned(savedGameEarned);
      setBoost(savedBoostRaw ? JSON.parse(savedBoostRaw) : null);
    }

    loadData();

    const interval = setInterval(() => {
      setNow(Date.now());
      loadData();
    }, 1000);

    return () => clearInterval(interval);
  }, []);

  const boostActive = !!boost && boost.expiresAt > now;
  const boostSecondsLeft = boostActive
    ? Math.max(0, Math.floor((boost!.expiresAt - now) / 1000))
    : 0;

  const estimatedOnChain = useMemo(() => {
    // Simple early-stage estimate:
    // 60% of total game earned + current passive claimable
    return Math.floor(totalGameEarned * 0.6 + claimable);
  }, [totalGameEarned, claimable]);

  const totalEcosystemValue = useMemo(() => {
    return Math.floor(labBalance + claimable + totalGameEarned);
  }, [labBalance, claimable, totalGameEarned]);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-black tracking-tight">Rewards</h1>
        <p className="mt-2 text-white/60">
          Track what you have earned, what is claimable now, and what could
          later convert into your live token economy.
        </p>
      </div>

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <RewardCard
          label="Lab Balance"
          value={`${Math.floor(labBalance)} SPRM`}
          hint="Spendable inside the app right now"
        />
        <RewardCard
          label="Passive Claimable"
          value={`${Math.floor(claimable)} SPRM`}
          hint="Generated by your room over time"
        />
        <RewardCard
          label="Game Earned"
          value={`${Math.floor(totalGameEarned)} SPRM`}
          hint="Lifetime earned from gameplay"
        />
        <RewardCard
          label="Estimated Future Claim"
          value={`${estimatedOnChain} SPRM`}
          hint="Early snapshot estimate, not on-chain yet"
        />
      </div>

      <div className="grid gap-6 xl:grid-cols-[1fr_360px]">
        <section className="space-y-4">
          <div className="rounded-3xl border border-white/10 bg-white/5 p-6">
            <div className="text-sm uppercase tracking-[0.25em] text-pink-300/70">
              Reward Summary
            </div>

            <div className="mt-4 grid gap-4 md:grid-cols-2">
              <InfoBlock
                title="Current In-App Value"
                value={`${totalEcosystemValue} SPRM`}
                description="Combined view of balance, claimable output, and game-generated earnings."
              />
              <InfoBlock
                title="Live Boost Status"
                value={boostActive ? `x${boost!.multiplier}` : "Inactive"}
                description={
                  boostActive
                    ? `Ends in ${boostSecondsLeft}s`
                    : "No active production boost running"
                }
              />
            </div>
          </div>

          <div className="rounded-3xl border border-white/10 bg-white/5 p-6">
            <div className="text-sm uppercase tracking-[0.25em] text-emerald-300/70">
              How Rewards Work
            </div>

            <div className="mt-4 space-y-3 text-sm text-white/70">
              <div>• Play runs add SPRM directly into your Lab balance.</div>
              <div>• Your room generates passive output over time.</div>
              <div>• Passive output sits in claimable storage until collected.</div>
              <div>• Boosts temporarily increase passive generation.</div>
              <div>
                • Later, part of this system can map into your on-chain token economy.
              </div>
            </div>
          </div>

          <div className="rounded-3xl border border-white/10 bg-white/5 p-6">
            <div className="text-sm uppercase tracking-[0.25em] text-fuchsia-300/70">
              Early Player Advantage
            </div>

            <div className="mt-4 text-sm leading-7 text-white/70">
              You are building progress before the token is fully live on-chain.
              That means your room strength, accumulated earnings, and total activity
              can all become part of a stronger early-user position later.
            </div>
          </div>
        </section>

        <aside className="space-y-4">
          <div className="rounded-3xl border border-white/10 bg-white/5 p-5">
            <div className="text-sm uppercase tracking-[0.25em] text-amber-300/70">
              Snapshot View
            </div>

            <div className="mt-4 space-y-3 text-sm text-white/70">
              <Row label="Lab Balance" value={`${Math.floor(labBalance)} SPRM`} />
              <Row label="Passive Claimable" value={`${Math.floor(claimable)} SPRM`} />
              <Row label="Game Earned" value={`${Math.floor(totalGameEarned)} SPRM`} />
              <Row label="Estimated Future Claim" value={`${estimatedOnChain} SPRM`} />
            </div>
          </div>

          <div className="rounded-3xl border border-white/10 bg-white/5 p-5">
            <div className="text-sm uppercase tracking-[0.25em] text-red-300/70">
              Boost Monitor
            </div>

            <div className="mt-4 rounded-2xl border border-white/10 bg-black/20 p-4">
              {boostActive ? (
                <div className="space-y-2">
                  <div className="text-lg font-bold text-white">
                    Overdrive Active
                  </div>
                  <div className="text-sm text-white/60">
                    Multiplier: x{boost!.multiplier}
                  </div>
                  <div className="text-sm text-white/60">
                    Time left: {boostSecondsLeft}s
                  </div>
                </div>
              ) : (
                <div className="space-y-2">
                  <div className="text-lg font-bold text-white">
                    No Active Boost
                  </div>
                  <div className="text-sm text-white/60">
                    Activate boosts in the Lab to increase passive output.
                  </div>
                </div>
              )}
            </div>
          </div>

          <div className="rounded-3xl border border-white/10 bg-white/5 p-5">
            <div className="text-sm uppercase tracking-[0.25em] text-white/55">
              Notes
            </div>

            <div className="mt-4 space-y-3 text-sm text-white/65">
              <div>• Rewards shown here are still off-chain.</div>
              <div>• The future claim estimate is only a preview.</div>
              <div>• Spendable Lab Balance is your live in-app economy.</div>
            </div>
          </div>
        </aside>
      </div>
    </div>
  );
}

function RewardCard({
  label,
  value,
  hint,
}: {
  label: string;
  value: string;
  hint: string;
}) {
  return (
    <div className="rounded-3xl border border-white/10 bg-white/5 p-5">
      <div className="text-sm text-white/50">{label}</div>
      <div className="mt-2 text-2xl font-black">{value}</div>
      <div className="mt-2 text-sm text-white/55">{hint}</div>
    </div>
  );
}

function InfoBlock({
  title,
  value,
  description,
}: {
  title: string;
  value: string;
  description: string;
}) {
  return (
    <div className="rounded-2xl border border-white/10 bg-black/20 p-5">
      <div className="text-sm text-white/50">{title}</div>
      <div className="mt-2 text-2xl font-black">{value}</div>
      <div className="mt-3 text-sm text-white/60">{description}</div>
    </div>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between">
      <span>{label}</span>
      <span className="font-bold text-white">{value}</span>
    </div>
  );
}