"use client";

import { useEffect, useMemo, useState } from "react";

type ActiveBoost = {
  multiplier: number;
  expiresAt: number;
};

export default function WalletPage() {
  const [labBalance, setLabBalance] = useState(0);
  const [claimable, setClaimable] = useState(0);
  const [totalGameEarned, setTotalGameEarned] = useState(0);
  const [boost, setBoost] = useState<ActiveBoost | null>(null);
  const [now, setNow] = useState(Date.now());

  // Placeholder until wallet integration is live
  const [walletConnected] = useState(false);
  const [walletAddress] = useState<string | null>(null);

  useEffect(() => {
    function loadData() {
      setLabBalance(Number(localStorage.getItem("wh_lab_balance") || 0));
      setClaimable(Number(localStorage.getItem("wh_claimable") || 0));
      setTotalGameEarned(Number(localStorage.getItem("wh_total_game_earned") || 0));

      const savedBoost = localStorage.getItem("wh_boost");
      setBoost(savedBoost ? JSON.parse(savedBoost) : null);
    }

    loadData();

    const interval = setInterval(() => {
      setNow(Date.now());
      loadData();
    }, 1000);

    return () => clearInterval(interval);
  }, []);

  const boostActive = !!boost && boost.expiresAt > now;
  const boostSecondsLeft = boostActive
    ? Math.max(0, Math.floor((boost!.expiresAt - now) / 1000))
    : 0;

  const estimatedFutureClaim = useMemo(() => {
    return Math.floor(totalGameEarned * 0.6 + claimable);
  }, [totalGameEarned, claimable]);

  const walletStatus = walletConnected ? "Connected" : "Not Connected";
  const launchPhase = "Pre-Launch";
  const tokenStatus = "Off-chain progression active";

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-black tracking-tight">Wallet</h1>
        <p className="mt-2 text-white/60">
          Track your current reward state, token readiness, and future on-chain
          position as the ecosystem goes live.
        </p>
      </div>

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <WalletStat label="Wallet Status" value={walletStatus} />
        <WalletStat label="Launch Phase" value={launchPhase} />
        <WalletStat label="Token Status" value={tokenStatus} />
        <WalletStat label="Estimated Future Claim" value={`${estimatedFutureClaim} SPRM`} />
      </div>

      <div className="grid gap-6 xl:grid-cols-[1fr_360px]">
        <section className="space-y-4">
          <div className="rounded-3xl border border-white/10 bg-white/5 p-6">
            <div className="text-sm uppercase tracking-[0.25em] text-pink-300/70">
              Wallet Overview
            </div>

            <div className="mt-4 grid gap-4 md:grid-cols-2">
              <InfoCard
                title="Lab Balance"
                value={`${Math.floor(labBalance)} SPRM`}
                description="Spendable inside your current in-app economy."
              />
              <InfoCard
                title="Passive Claimable"
                value={`${Math.floor(claimable)} SPRM`}
                description="Generated by your room and waiting to be claimed."
              />
              <InfoCard
                title="Game Earned"
                value={`${Math.floor(totalGameEarned)} SPRM`}
                description="Lifetime SPRM earned through gameplay."
              />
              <InfoCard
                title="Boost Status"
                value={boostActive ? `x${boost!.multiplier}` : "Inactive"}
                description={
                  boostActive
                    ? `Boost ends in ${boostSecondsLeft}s`
                    : "No active production boost running"
                }
              />
            </div>
          </div>

          <div className="rounded-3xl border border-white/10 bg-white/5 p-6">
            <div className="text-sm uppercase tracking-[0.25em] text-emerald-300/70">
              Token Readiness
            </div>

            <div className="mt-4 space-y-3 text-sm text-white/70">
              <div>• Your current progress is already being saved.</div>
              <div>• Lab balance is live inside the app.</div>
              <div>• Room output continues to build passive value.</div>
              <div>• Estimated future claim previews what may later map on-chain.</div>
              <div>• Wallet connection and live claim flow can be added in the next phase.</div>
            </div>
          </div>

          <div className="rounded-3xl border border-white/10 bg-white/5 p-6">
            <div className="text-sm uppercase tracking-[0.25em] text-fuchsia-300/70">
              Why Users Benefit Now
            </div>

            <div className="mt-4 space-y-3 text-sm text-white/70">
              <div>• They build progress before the token goes fully live.</div>
              <div>• They upgrade their room and improve passive generation.</div>
              <div>• They accumulate game-earned value and early-user advantage.</div>
              <div>• Their position becomes stronger before on-chain competition begins.</div>
            </div>
          </div>
        </section>

        <aside className="space-y-4">
          <div className="rounded-3xl border border-white/10 bg-white/5 p-5">
            <div className="text-sm uppercase tracking-[0.25em] text-amber-300/70">
              Account Snapshot
            </div>

            <div className="mt-4 space-y-3 text-sm text-white/70">
              <Row label="Wallet" value={walletConnected ? "Connected" : "Not connected"} />
              <Row label="Address" value={walletAddress ?? "—"} />
              <Row label="Lab Balance" value={`${Math.floor(labBalance)} SPRM`} />
              <Row label="Claimable" value={`${Math.floor(claimable)} SPRM`} />
              <Row label="Game Earned" value={`${Math.floor(totalGameEarned)} SPRM`} />
            </div>
          </div>

          <div className="rounded-3xl border border-white/10 bg-white/5 p-5">
            <div className="text-sm uppercase tracking-[0.25em] text-red-300/70">
              Boost Monitor
            </div>

            <div className="mt-4 rounded-2xl border border-white/10 bg-black/20 p-4">
              {boostActive ? (
                <div className="space-y-2">
                  <div className="text-lg font-bold text-white">Overdrive Active</div>
                  <div className="text-sm text-white/60">
                    Multiplier: x{boost!.multiplier}
                  </div>
                  <div className="text-sm text-white/60">
                    Time left: {boostSecondsLeft}s
                  </div>
                </div>
              ) : (
                <div className="space-y-2">
                  <div className="text-lg font-bold text-white">No Active Boost</div>
                  <div className="text-sm text-white/60">
                    Activate boosts in the Lab to strengthen passive output.
                  </div>
                </div>
              )}
            </div>
          </div>

          <div className="rounded-3xl border border-white/10 bg-white/5 p-5">
            <div className="text-sm uppercase tracking-[0.25em] text-white/55">
              Launch Notes
            </div>

            <div className="mt-4 space-y-3 text-sm text-white/65">
              <div>• Current economy is active in-app.</div>
              <div>• SPRM token is not yet claimable on-chain.</div>
              <div>• Future wallet connection will handle live claiming.</div>
              <div>• Early progress may become a strong launch advantage.</div>
            </div>
          </div>
        </aside>
      </div>
    </div>
  );
}

function WalletStat({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-3xl border border-white/10 bg-white/5 p-5">
      <div className="text-sm text-white/50">{label}</div>
      <div className="mt-2 text-2xl font-black">{value}</div>
    </div>
  );
}

function InfoCard({
  title,
  value,
  description,
}: {
  title: string;
  value: string;
  description: string;
}) {
  return (
    <div className="rounded-2xl border border-white/10 bg-black/20 p-5">
      <div className="text-sm text-white/50">{title}</div>
      <div className="mt-2 text-2xl font-black">{value}</div>
      <div className="mt-3 text-sm text-white/60">{description}</div>
    </div>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between gap-3">
      <span>{label}</span>
      <span className="text-right font-bold text-white">{value}</span>
    </div>
  );
}